### ISSUE TITLE
Machine building

### ISSUE THREAD

**Issue by rozmy** [yoyo2324/PocketFactory#2]
**Building a machine is a 4 step process**
1. Open machine list from Navbar
2. Select machine type from list 
3. Select position by tapping on grid. Tap and hold rotates machine
4. Confirm / Dismiss

**1, Open machine list from Navbar**
- [x] Make a navigation bar to bottom, and add a "Build" button

**2, Select machine type from list** 
Item contents: Machine graphics, Name, Price
List order: Unlocked, Locked
Full unlocked order:
- Starter
- Seller
- Roller
- Crafter
- Furnace
- Cutter
- Wire Drawer
- Left Selector
- Right Selector
- Robotic Arm
- Timed Roller
- Multi Selector
- Left Splitter
- Right Splitter
- Multi Splitter
- Hydraulic Press
- Transporter Input
- Transporter Output

- [x] All unlocked machines can be disabled, when there is not enough money.
- [x] You can navigate back by clicking on the close button

**3, Tap to the grid to place machines.**
- [x] On this step a new grid layer appears
- [x] A new instruction appears: "Tap on grid to place a MachineName"
- [x] You can navigate back by tapping on back button
- [x] Tapping on any empty cell places a new machine. 
- [x] Check price (if not enough, don’t place a new machine) 
- [x] Check collision
- Existing Machines
- Factory borders (building is not available outside the factory zone)
- The same cell can be selected just once
  
**4, Confirm / Dismiss** 
- [x]  Display machine's type and  add instructions
- [x]  If at least 1 machine is placed, show 2 new buttons, one for “Build” and one for “Dismiss”
- [x] Clicking on build hides the grid, builds the selected machine(s) and sets the UI to default view
- [x] Dismiss just reverts the UI to default

![image](https://user-images.githubusercontent.com/7920792/62557488-62388100-b877-11e9-8dae-c28facb17611.png)

**Comment by destrugter** [comment]
What are the sizes of the different objects?

**Comment by rozmy** [comment]
![image](https://user-images.githubusercontent.com/7920792/63602459-c8d3d380-c5c7-11e9-8f0f-ba4b224cd4d0.png)
