### ISSUE TITLE
Build mode improvements

### ISSUE THREAD

**Issue by rozmy** [yoyo2324/PocketFactory#20]
We already mentioned these in discord, here are my test cases for the record
- [x] When accepting a set of new machines, clicking on OK button builds a new machine below the UI
- [x] Cannot close the machine settings modal when a machine is below the UI
- [x] When a Modal is open, the canvas should not pan when dragging the modal's content (eg.: resource list in starters)
- [x] Resources shouldn't prevent tapping (eg.: tapping on a block of ore should open the machine settings below it)

Other mobile-related interactions
- [x] In build mode do not build on tap and drag, place machines one by one
- [x] In build mode tap and drag should rotate the placed machine
- [x] enable two-finger pan

**Comment by destrugter** [comment]
"In build mode tap and drag should rotate the placed machine"

This would override the ability to pan the camera while in build mode

**Comment by rozmy** [comment]
> "In build mode tap and drag should rotate the placed machine"
> 
> This would override the ability to pan the camera while in build mode

Yes, this! You can use Double tap + hold to drag the camera in build mode.
