### ISSUE TITLE
Bulk editing

### ISSUE THREAD

**Issue by rozmy** [yoyo2324/PocketFactory#3]
- [x] open bulk mode from navbar
- [x] select multiple machines by tapping, pan with 2 fingers
- [x] select action (move, rotate, flip,save blueprint, delete)
   - [x] Move
   - [x] Rotate
   - [x] Flip
   - [x] Save Blueprint
   - [x] Delete (Sell)
- [x] each action has a confirm step

**Comment by destrugter** [comment]
- [ ] open bulk mode from navbar
- [ ] select multiple machines by tapping, pan with 2 fingers
- [ ] select action (move, rotate, flip,save blueprint, delete)
- [ ] each action has a confirm step
