### ISSUE TITLE
Bulk/Select Mode improvements

### ISSUE THREAD

**Issue by rozmy** [yoyo2324/PocketFactory#33]
- [x] two-finger zoom closes the select mode, it should let the user pan and zoom as they want

- [x] when nothing is selected, disable OK button, only cancel should work

- [x] selecting more devices using the tap-and-hold rectangle selects incorrectly (xor instead of and?) 
How to reproduce:
- place 3 machines next to each other
- select 1
- tap-and-hold both 3 items
- selection Will be inverted(2) instead of all (3)

- [x] tap-and-hold selection should instantly show what's selected. Now it fires onRelelease.

- [x] enable two  finger pan in this mode

**Comment by destrugter** [comment]
I'm treating selection like a toggle. If you select a machine and then select it again, it will deselect the machine. Should the behavior be altered?
